# Generated by Django 3.1.2 on 2020-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20201014_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='sensor_dato',
            name='ubicacion',
            field=models.CharField(choices=[('SAM', 'Sampacho'), ('RC', 'Rio Cuarto'), ('GD', 'General Deheza')], default='SAM', max_length=50),
        ),
    ]
