# Generated by Django 3.1.2 on 2020-10-19 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20201015_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_dato',
            name='humedad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sensor_dato',
            name='presion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(885), django.core.validators.MaxValueValidator(1077)]),
        ),
        migrations.AlterField(
            model_name='sensor_dato',
            name='temperatura',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
