site_name: Documentación
nav:
    - Home: index.md
    - Información: informacion.md
    - Servicios: servicios.md
    - Generación de tráfico: generacionDeTrafico.md
    - Adquisición de métricas: adquisicionDeMetricas.md
    - Visualización de métricas: visualizacionDeMetricas.md
    - Pruebas de Performance: PruebasPerformance.md
theme: 
    name: 'material'
    font:
     text: ubuntu

