# Generated by Django 3.1.2 on 2020-10-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(choices=[('SAM', 'Sampacho'), ('RC', 'Rio Cuarto'), ('GD', 'General Deheza')], default='SAM', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sensor_dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.IntegerField(max_length=50)),
                ('presion', models.IntegerField(max_length=50)),
                ('humedad', models.IntegerField(max_length=50)),
                ('fecha', models.DateField()),
                ('nombre_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.sensor')),
            ],
        ),
    ]
