# Generated by Django 3.1.2 on 2020-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_dato',
            name='humedad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor_dato',
            name='presion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor_dato',
            name='temperatura',
            field=models.IntegerField(),
        ),
    ]
